51 prepare facebook and instagram data for n mixture model
OxfordDemSci/UkraineNowPop pull request #52
Opened 2024-10-16 13:42 UTC by edarin

See comments in #51 

There are two scripts to address the issue, both stored in src/1_pop_data:

[10_daily_audience.py](https://github.com/OxfordDemSci/UkraineNowPop/blob/51-prepare-facebook-and-instagram-data-for-n-mixture-model/src/1_pop_data/10_daily_audience.py)
it is now set to query one year of Facebook and Instagram data for the T_13Plus. Output is stored in 2023_WHO_Ukraine_Population\\output\\population_proxy\\social_media_audience\ua_[platform]_audience.csv.

[11_process_daily_audience.R](https://github.com/OxfordDemSci/UkraineNowPop/blob/51-prepare-facebook-and-instagram-data-for-n-mixture-model/src/1_pop_data/11_process_daily_audience.R)
It has a function to convert the audience into a 3d array [week, oblast, day_of_week].
The output for the models are stored in 2023_WHO_Ukraine_Population\\output\\population_proxy\\model_data\[platform]_md.rds.
It creates also a dataframe summarising missing observations per oblast, week and day of the week.
image.
I would advise to remove at least weeks that have less than one observation per oblast (n_obs).
It is stored in 2023_WHO_Ukraine_Population\\output\\population_proxy\\model_data\[platform]_md_missing.rds

2024-10-18 16:23 UTC, doug-leasure requested changes
This is looking good, @edarin . Thank you. 

I don't think we need to drop weeks with no data because we will still model the population for those weeks. I will do some processing on the model prep side to take care of that bit. 

Would you mind updating your code so that the `md` object you produce matches the simulated data object? I put an example in `.../population_proxy/model_data/template_md.rds` . The elements in the list object are:

I = the total number of locations
T = total number of weeks
M = matrix (T x I) with the number of repeat observations available each week (i.e. 0 - 7)
y = array (T x I x max(M)) with the counts of active users.

You do not need to include `p_true`, `N_true`, or `seed`.

2024-10-21 15:37 UTC, edarin commented
Done!

2024-10-23 14:04 UTC, doug-leasure approved these changes

2024-10-23 14:04 UTC, merged

2024-10-23 15:43 UTC, doug-leasure commented
@edarin I added commit 966e827d6cbc4def6aaf99ccdf186576a0df4bd7 with a few edits following up on this PR.