58 standardise model inputs
OxfordDemSci/UkraineNowPop pull request #64
Opened 2024-11-04 15:23 UTC by edarin

2024-11-04 15:35 UTC, alaparicioc commented on src/1_pop_data/10_create_master_index.R
> +agesex <- c("T_13Plus")
here is where we define the groups we want, right?

2024-11-04 16:23 UTC, edarin commented on src/1_pop_data/10_create_master_index.R
> +agesex <- c("T_13Plus")
yep. and i created a function if you want them regularly spaced as you mentionned.

2024-11-04 16:24 UTC, edarin commented on src/1_pop_data/10_create_master_index.R
> +agesex <- c("T_13Plus")
i left some commented age group for the reader to know the format expected

2024-11-05 11:41 UTC, doug-leasure requested changes
Hey @edarin... nice work... and FAST! Thanks for this. 

Could you take a look at my comments on standardising column naming in scripts 10 and 20?

2024-11-05 11:41 UTC, doug-leasure commented on src/1_pop_data/10_create_master_index.R
> +source("R_helpers/generic.R")
It might be better to simply put the relevant bits of this code at the top of each script. This is loading quite a few packages that are not needed for this otherwise simple script which I needed to install before I could actually use the script.

2024-11-05 11:41 UTC, doug-leasure commented on src/1_pop_data/10_create_master_index.R
> +master_index <- expand_grid(
Can we please standardise the naming of these columns and their contents? For each index, I would like a numeric "key" and an optional "name". 

For example, "t_key" would be the date of the Monday beginning each week in the format 20220225 so that it is fully numeric and can be included in the Stan data object, while "t_name" could be the ISO date format "2022-02-25" as a string. 

"i_key" is the numeric meta_key and "i_name" is the meta_name. 

"a_key" is maybe 013999 (for 13Plus) and "a_name" is "13Plus"

"s_key" is 0 for both, 1 for male and 2 for female (to match Meta) and "s_name" is "T", "M", or "F"

This standardisation will help avoid the need to revise downstream code as these column names potentially chnage for vairous source data, and also the numeric keys will allow these reference keys to be included with the model data to reduce dependence on keeping the master_index alongside the model results that it goes with.

2024-11-05 11:41 UTC, doug-leasure commented on src/1_pop_data/20_prepare_sma_data.R
> +sma_facebook_processed <- process_sma_data(sma_facebook)
Could we please rename the "dau" column in the final processed data to be "value".  We can use the "output_label" to indicate that the csv represents dau or mau while keeping the column names standardised to help downstream code compatibility.

I think we can also drop the "collection_date" column as it should already be encoded in the master_index via the t_key.

2024-11-05 12:37 UTC, edarin commented on src/1_pop_data/10_create_master_index.R
> +master_index <- expand_grid(
a_key cant be 01.. as it will be stored as a numeric for stan and therefore will loose its leading 0.
I would therefore recommend to have age_max being always three digits long but age_min being whatever age_min is.

2024-11-05 13:57 UTC, doug-leasure requested changes
See comment on script 20, line 54

2024-11-05 13:57 UTC, doug-leasure commented on src/1_pop_data/20_prepare_sma_data.R
> +    left_join(time_index_expanded ) |>
The left_join fails here with this message:
```
> sma_facebook_processed <- process_sma_data(sma_facebook)
Joining with `by = join_by(t_name)`
Error in `left_join()`:
! `by` must be supplied when `x` and `y` have no common variables.
ℹ Use `cross_join()` to perform a cross-join.
```

2024-11-06 14:12 UTC, doug-leasure requested changes
A couple of changes needed in master_index.csv:
1. The s index contains only zeros. The index values should always be integers greater than zero.
2. s_name contains values TRUE where it should be "T".

2024-11-06 14:23 UTC, alaparicioc commented
The weekly step that you are including is every Monday, right? I thougth it was going to be Sundays. My question is because the mean of the Instagram and Facebook ratios are calculated in the 1_base_model_config.R. Would not we assume that the trend of Mondays are based on what happened on the rest of the week?

2024-11-06 14:37 UTC, edarin commented
>  A couple of changes needed in master_index.csv:
    The s index contains only zeros.

This is normal for all. such that it's 1 and 2 for male and female.


> The index values should always be integers greater than zero.
    s_name contains values TRUE where it should be "T".

It is T. It is when you are reading it that t is being read as TRUE. I have this line of code to avoid it.
  `col_types = c(s_name = 'c'))` [in](https://github.com/OxfordDemSci/UkraineNowPop/blob/65b4d3249766d232e892062520f02444f413e46b/src/1_pop_data/20_prepare_sma_data.R#L16)



> The weekly step that you are including is every Monday, right? 

It is monday. Let me know if you need another day.

2024-11-06 14:58 UTC, doug-leasure commented
Okay, thanks. All good for the Ts. 

On indexing, all indexes are required by R, JAGS, and Stan to be integers 1 and above. It is fine for s_key to have zeros, but the column s has to be 1 and above.

2024-11-06 15:03 UTC, doug-leasure commented
> The weekly step that you are including is every Monday, right? I thougth it was going to be Sundays. My question is because the mean of the Instagram and Facebook ratios are calculated in the 1_base_model_config.R. Would not we assume that the trend of Mondays are based on what happened on the rest of the week?

@alaparicioc  The model_config code should be defining the week to start on Mondays. This is what I thought we agreed. I meant for the config code to be calculating the FG ratio means for Monday-Sunday, but maybe I messed that up?

2024-11-08 22:52 UTC, doug-leasure submitted a review, later dismissed

2024-11-08 22:54 UTC, doug-leasure approved these changes
@edarin , I made the change to the s index while working on a bug in the t index. Please take a look at my changes in commit 28e6836 so that you are aware.

2024-11-08 23:23 UTC, merged