77 age sex index
OxfordDemSci/UkraineNowPop pull request #79
Opened 2024-11-19 12:41 UTC by edarin

2024-11-19 13:57 UTC, alaparicioc requested changes
__I cannot comment on the line of code, but s should be integer, not numeric. Something like s = s_name |> as_factor() |> as.integer(),

2024-11-19 13:57 UTC, alaparicioc commented on src/1_pop_data/10_create_master_index.R
> +  arrange(age_min, desc(agesex)) |>
I cannot comment on the line of code, but s should be integer, not numeric. Something like s = s_name |> as_factor() |> as.integer(),

2024-11-19 16:33 UTC, edarin commented on src/1_pop_data/10_create_master_index.R
> +  arrange(age_min, desc(agesex)) |>
Done! https://github.com/OxfordDemSci/UkraineNowPop/commit/448227b01b1a2b587fb18337719b6b7c2d060806
Weird that you cant commit change?
Sorry for the cumbersome process. Do you want to check together why you cant commit?

2024-11-20 13:41 UTC, merged

2024-11-21 06:13 UTC, alaparicioc commented on src/1_pop_data/10_create_master_index.R
> +  arrange(age_min, desc(agesex)) |>
thansl! At some point,we can check togther how I am commiting. It may be online though.