80 standardise covariates
OxfordDemSci/UkraineNowPop pull request #83
Opened 2024-11-22 18:24 UTC by edarin

First draft!
It doesnt entail the geographical scaling.

It entails:
- the imputation of `pwtt` as repeating the last observation
- the cumulative value with three windows: 1, 3 and 6 months (called `value_sumXmonth`)
- the temporal scaling with three windows: 1, 3 and 6 months (called `value_meanXmonth`)
- the standardised version of the raw, the cumulative and the temporal scaled covariate.

Note that it's not really 1, 3, 6 months but 4, 12 and 24 weeks.
2nd note: please re-run all the covariates pre-processing.

2024-11-22 20:42 UTC, doug-leasure commented on src/covariates/collection/deepstate.py
> +    if download:
If the id's from HISTORY_URL are stable through time, then it might be better to check if each file exists and then download it if it doesn't exist rather than requiring a download toggle. 

But, I'm not sure those id's are stable, so I think this download toggle is good.

2024-11-22 20:50 UTC, doug-leasure commented on src/covariates/collection/pwtt.py
> +# impute pwtt for missing dates by propogating the last valid observation forward to the next valid
Would it make more sense to move imputation for missing dates (i.e. true NAs where there were no images available) to a separate script in the "processing" folder?

2024-11-22 22:16 UTC, doug-leasure commented on src/covariates/collection/pwtt.py
> +admin_sum_lg['pwtt'] = admin_sum_lg.sort_values(['i', 't']).groupby('i')['pwtt'].fillna(method='ffill')
This line of code raises a FutureWarning and will eventually cause an error. Here is the warning which specifies the solution: 
```
<positron-console-cell-24>:1: FutureWarning: SeriesGroupBy.fillna is deprecated and will be removed in a future version. Use obj.ffill() or obj.bfill() for forward or backward filling instead. If you want to fill with a single value, use Series.fillna instead
<positron-console-cell-24>:1: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
```

2024-11-22 22:40 UTC, doug-leasure commented on src/covariates/processing/10_combine_stockVariables.R
> +    value_sum1month_std = (value_sum1month - mean(value_sum1month, na.rm = T)) / sd(value_sum1month, na.rm = T),
I think we want only a single "value" column. Otherwise, I'm afraid that these multiple value columns will get unwieldy. 

Can we add the following columns and keep the data in long format? 
1. sum_stat = name of the summary statistic used (e.g. NA, mean, sum, sd)
2. time_scale = time window used (e.g. NA, -1mo, -3mo, +1mo, +3mo)
3. spatial_scale = spatial scale used (e.g. NA, neighbours, macroregion)
4. scale_mean = the mean used for rescaling the covariate (or NA if not scaled)
5. scale_sd = the sd used for rescaling the covariate (or NA if not scaled)

This will also make it quite easy to produce a second csv that is a catalogue of covariates by saving the distinct values from these columns and the "covariate" column.

2024-11-22 22:43 UTC, doug-leasure commented on src/covariates/processing/10_combine_stockVariables.R
> +# this doesnt work for me in positron, any idea?
It worked for me, but with the following warnings: 
```
Warning messages:
1: Removed 10 rows containing missing values or values outside the scale range (`geom_point()`).
2: Removed 66 rows containing missing values or values outside the scale range (`geom_point()`).
3: Removed 15 rows containing missing values or values outside the scale range (`geom_point()`).
4: Removed 44 rows containing missing values or values outside the scale range (`geom_point()`).
5: Removed 186 rows containing missing values or values outside the scale range (`geom_point()`).
6: Removed 50 rows containing missing values or values outside the scale range (`geom_path()`).
7: Removed 404 rows containing missing values or values outside the scale range (`geom_point()`).
8: Removed 401 rows containing missing values or values outside the scale range (`geom_path()`).
9: Removed 15 rows containing missing values or values outside the scale range (`geom_point()`).
10: Removed 96 rows containing missing values or values outside the scale range (`geom_point()`).
11: Removed 44 rows containing missing values or values outside the scale range (`geom_point()`).
12: Removed 120 rows containing missing values or values outside the scale range (`geom_point()`).
13: Removed 186 rows containing missing values or values outside the scale range (`geom_point()`).
14: Removed 50 rows containing missing values or values outside the scale range (`geom_path()`).
15: Removed 437 rows containing missing values or values outside the scale range (`geom_point()`).
16: Removed 437 rows containing missing values or values outside the scale range (`geom_path()`).
17: Removed 265 rows containing missing values or values outside the scale range (`geom_point()`).
18: Removed 159 rows containing missing values or values outside the scale range (`geom_path()`).
19: Removed 351 rows containing missing values or values outside the scale range (`geom_point()`).
20: Removed 103 rows containing missing values or values outside the scale range (`geom_path()`).
21: Removed 112 rows containing missing values or values outside the scale range (`geom_point()`).
22: Removed 10 rows containing missing values or values outside the scale range (`geom_path()`).
```

2024-11-22 22:50 UTC, doug-leasure requested changes
This all looks great! I was able to re-run everything with no problems (other than a missing dependency, which I added to requirements.R). 

I left a few comments for you to consider, but only one of them I think actually requires a change. You have added various different "value" columns in wide format (in `10_combine_stockVariables.R`), but I think we need to stay with long format. To achieve this, we just need to add a few columns to specify attributes of scaling applied. I have given some suggestions.

2024-11-24 09:02 UTC, doug-leasure commented on src/covariates/processing/10_combine_stockVariables.R
> +  mutate(
We are getting NAs for some scaled covariates that actually have data. 

For example, "acled_withfatalities" contains NAs for "value_mean1month_std" although the raw data have values of zero. Maybe this is when the standard deviation used in the denominator for scaling is zero?

2024-11-24 12:40 UTC, doug-leasure commented on src/covariates/collection/deepstate.py
I think we want a version of this covariate that is proportion of the area of the oblast that is occupied. We can probably use this unscaled in the model.

2024-11-24 12:41 UTC, doug-leasure commented on src/covariates/processing/10_combine_stockVariables.R
> +    value_sum1month_std = (value_sum1month - mean(value_sum1month, na.rm = T)) / sd(value_sum1month, na.rm = T),
I think we probably want to include unscaled versions of the covariates in the final data as well. For example, proportion of oblasts occupied would be a covariate that I would try to use unscaled.

2024-11-26 11:52 UTC, edarin commented on src/covariates/collection/pwtt.py
> +# impute pwtt for missing dates by propogating the last valid observation forward to the next valid
I hesitated as it's only one variable.
Done: https://github.com/OxfordDemSci/UkraineNowPop/commit/4745dc534a1264c6283539a23b6d7970efcbe09b

2024-11-26 12:01 UTC, edarin commented on src/covariates/collection/pwtt.py
> +admin_sum_lg['pwtt'] = admin_sum_lg.sort_values(['i', 't']).groupby('i')['pwtt'].fillna(method='ffill')
Fixed with: https://github.com/OxfordDemSci/UkraineNowPop/commit/4745dc534a1264c6283539a23b6d7970efcbe09b

2024-11-26 15:37 UTC, edarin commented on src/covariates/processing/10_combine_stockVariables.R
> +  mutate(
Yes it is because of sd=0. What would you prefer here? The min sd observed for this covariate? 0.1?

2024-11-27 14:47 UTC, edarin commented on src/covariates/processing/10_combine_stockVariables.R
> +    value_sum1month_std = (value_sum1month - mean(value_sum1month, na.rm = T)) / sd(value_sum1month, na.rm = T),
Done

2024-11-27 15:54 UTC, edarin commented on src/covariates/collection/deepstate.py
Done https://github.com/OxfordDemSci/UkraineNowPop/commit/0dee7adf3ec7bd5a2f27b4b7c834438d1a0e6242

2024-11-27 18:03 UTC, doug-leasure commented
@edarin, can you please make sure to include the mean and sd used for scaling in the final data? 

I would suggest these column names:
time_std, space_std, center_std, scale_sd, value_std

Everything worked well for me, so please go ahead an merge when this last bit is done.

2024-11-27 18:04 UTC, doug-leasure approved these changes

2024-11-28 10:47 UTC, merged